src/main/java/com/exablack/router/train/model/Path.java
package com.exablack.router.train.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * Representacao do caminho entre duas cidades, esta pode ser complementada com
 * informacoes como duracao, preco, tipo de tereno
 *
 * @author Bruno Carlo
 *
 */
@Entity
@XmlRootElement
@Table(name = "path")
public class Path implements Serializable {

	private static final long serialVersionUID = 2646556211051677540L;

	@Id
	@GeneratedValue
	@Column(name = "path_id", nullable = false)
	private Long id;

	@ManyToOne
	@JoinColumn(name = "path_origin_town_id", referencedColumnName = "town_id", nullable = false)
	private Town origin;

	@ManyToOne
	@JoinColumn(name = "path_destination_town_id", referencedColumnName = "town_id", nullable = false)
	private Town destination;

	@Column(name = "path_destination", nullable = false)
	private Double distance;

	public Long getId() {
		return this.id;
	}

	public void setId(final Long id) {
		this.id = id;
	}

	public Town getOrigin() {
		return this.origin;
	}

	public void setOrigin(final Town origin) {
		this.origin = origin;
	}

	public Town getDestination() {
		return this.destination;
	}

	public void setDestination(final Town destination) {
		this.destination = destination;
	}

	public Double getDistance() {
		return this.distance;
	}

	public void setDistance(final Double distance) {
		this.distance = distance;
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.id).append(this.origin).append(this.destination).toHashCode();
	}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (this.getClass() != obj.getClass()) {
			return false;
		}
		final Path other = (Path) obj;
		return new EqualsBuilder().append(this.id, other.id).append(this.origin, other.origin)
				.append(this.destination, other.destination).isEquals();
	}

	public String getRepresentPath() {
		return String.format("%s -> (%s) -> %s", this.origin.getName(), this.distance, this.destination.getName());
	}

	@Override
	public String toString() {
		return String.format("Path [id=%s, origin=%s, destination=%s, distance=%s]", this.id, this.origin,
				this.destination, this.distance);
	}

}

src/main/java/com/exablack/router/train/model/Town.java
package com.exablack.router.train.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * Representa uma cidade, pode ser complementada com informaações demograficas e
 * outras.
 *
 * @author Bruno Carlo
 */
@Entity
@XmlRootElement
@Table(name = "town", uniqueConstraints = @UniqueConstraint(columnNames = { "town_name" }))
public class Town implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -123243101044288359L;

	@Id
	@GeneratedValue
	@Column(name = "town_id", nullable = false)
	private Long id;

	@Column(name = "town_name", nullable = false, length = 200)
	private String name;

	@OneToMany
	@MapKey(name = "destination")
	@JoinColumn(name = "path_origin_town_id", referencedColumnName = "town_id", insertable = false, updatable = false)
	private Map<Town, Path> pathsTo;

	@OneToMany
	@MapKey(name = "origin")
	@JoinColumn(name = "path_destination_town_id", referencedColumnName = "town_id", insertable = false, updatable = false)
	private Map<Town, Path> pathsFrom;

	public Long getId() {
		return this.id;
	}

	public void setId(final Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.id).append(this.name).toHashCode();
	}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (this.getClass() != obj.getClass()) {
			return false;
		}
		final Town other = (Town) obj;
		return new EqualsBuilder().append(this.id, other.id).append(this.name, other.name).isEquals();
	}

	@Override
	public String toString() {
		return String.format("Town [id=%s, name=%s]", this.id, this.name);
	}

	public Map<Town, Path> getPathsTo() {
		return this.pathsTo;
	}

	public Map<Town, Path> getPathsFrom() {
		return this.pathsFrom;
	}

	public Path getPathTo(final Town destination) {
		return this.pathsTo != null ? this.pathsTo.get(destination) : null;
	}

	/**
	 * Adiciona um novo para desta cidade para outra
	 *
	 * @param destination
	 *            cidade destino
	 * @param path
	 *            caminho
	 */
	public void addPathTo(final Town destination, final Path path) {
		if (this.pathsTo == null) {
			this.pathsTo = new HashMap<>();
		}
		this.pathsTo.put(destination, path);
	}

	/**
	 * Adiciona um novo caminho que chega a esta cidade
	 *
	 * @param origin
	 *            cidade de origem
	 * @param path
	 *            caminho
	 */
	public void addPathFrom(final Town origin, final Path path) {
		if (this.pathsFrom == null) {
			this.pathsFrom = new HashMap<>();
		}
		this.pathsFrom.put(origin, path);
	}

}

src/main/java/com/exablack/router/train/controller/TrainRouterController.java
package com.exablack.router.train.controller;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.math.NumberUtils;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.TabChangeEvent;
import org.primefaces.event.UnselectEvent;
import org.primefaces.model.UploadedFile;

import com.exablack.router.train.model.Path;
import com.exablack.router.train.model.Town;
import com.exablack.router.train.service.Field;
import com.exablack.router.train.service.FilterTrip;
import com.exablack.router.train.service.Greatness;
import com.exablack.router.train.service.ServiceException;
import com.exablack.router.train.service.TownService;
import com.exablack.router.train.service.Trip;

/**
 * Menager Bean JSF provendo o controller para as paginas do site
 *
 * @author Bruno Carlo
 */
@ManagedBean(name = "trainRouter")
@ViewScoped
public class TrainRouterController {

	private List<Town> selectedTowns;

	private String typedGraph;

	private UploadedFile file;

	private Town originTown;

	private Town destinationTown;

	private String paths;

	private String tabIdSelected = "parameterFilter";

	private String tripFilterField;

	private String tripFilterGreatness;

	private String tripFilterValue;

	@EJB
	private TownService townService;

	public void upload() {
		if (this.file != null) {
			final String content = new String(this.file.getContents());

			try {
				this.townService.saveNewGraph(content);
				final FacesMessage message = new FacesMessage("Succesful", this.file.getFileName() + " is uploaded");
				FacesContext.getCurrentInstance().addMessage(null, message);
			} catch (final ServiceException e) {
				this.takeCareException(e);
			}
		}
	}

	public List<Town> getAllTowns() {
		try {
			final List<Town> towns = this.townService.getAllTowns();
			towns.sort((t1, t2) -> t1.getName().compareTo(t2.getName()));
			return towns;
		} catch (final ServiceException e) {
			this.takeCareException(e);
			return Collections.emptyList();
		}
	}

	private void takeCareException(final Exception e) {
		Logger.getLogger(this.getClass().getName()).log(java.util.logging.Level.SEVERE,
				e.fillInStackTrace().getMessage(), e);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getLocalizedMessage()));
	}

	public List<Town> selectedTown(final String query) {
		try {
			if (this.selectedTowns == null) {
				this.selectedTowns = new ArrayList<>();
			}

			final List<Town> towns = this.townService.getAllTowns();
			return towns.stream().filter((town) -> {
				return town.getName().startsWith(query) && !this.selectedTowns.contains(town);
			}).sorted((t1, t2) -> t1.getName().compareTo(t2.getName())).collect(Collectors.toList());
		} catch (final ServiceException e) {
			this.takeCareException(e);
			return Collections.emptyList();
		}
	}

	public void onSelectedTown(final SelectEvent event) {
		if ("path".equals(event.getComponent().getId())) {
			if (Town.class.isInstance(event.getObject())) {
				if (this.selectedTowns == null) {
					this.selectedTowns = new ArrayList<>();
				}
				this.selectedTowns.add((Town) event.getObject());
			}
		} else if ("inputOrigin".equals(event.getComponent().getId())) {
			this.originTown = (Town) event.getObject();
		} else if ("inputDestination".equals(event.getComponent().getId())) {
			this.destinationTown = (Town) event.getObject();
		}
	}

	public void onUnselectedTown(final UnselectEvent event) {
		if (Town.class.isInstance(event.getObject())) {
			if (this.selectedTowns != null) {
				this.selectedTowns.remove(event.getObject());
			}
		}
	}

	public void onTabChange(final TabChangeEvent event) {
		if (event.getTab() != null) {
			this.tabIdSelected = event.getTab().getId();
		}
	}

	public void calculePaths() {
		this.paths = "";
		if (this.originTown != null && this.destinationTown != null) {
			try {
				if ("minimumPath".equals(this.tabIdSelected)) {
					final List<Trip> trips = this.townService.getTrips(this.originTown, this.destinationTown,
							FilterTrip.SHORTEST_ROUTER);
					final Optional<Trip> trip = trips.stream()
							.sorted((t1, t2) -> t1.getTotalDistance().compareTo(t2.getTotalDistance())).findFirst();
					if (trip != null && trip.isPresent()) {
						this.paths = " A menor rota encontrada foi " + trip.get().getUnformatedPaths()
								+ " com a distancia de " + trip.get().getTotalDistance();
					} else {
						this.paths = "NO SUCH ROUTE";
					}
				} else if ("parameterFilter".equals(this.tabIdSelected)) {
					Field field = null;
					if (StringUtils.isNotBlank(this.tripFilterField)) {
						field = Field.valueOf(this.tripFilterField);
					}
					Greatness greatness = null;
					if (StringUtils.isNotBlank(this.tripFilterGreatness)) {
						greatness = Greatness.valueOf(this.tripFilterGreatness);
					}
					Double value = null;
					if (NumberUtils.isNumber(this.tripFilterValue)) {
						value = Double.valueOf(this.tripFilterValue);
					}
					if (field == null || greatness == null || value == null) {
						FacesContext.getCurrentInstance().addMessage(null,
								new FacesMessage("Para este calculo é necessario informar todos os parametros."));
					} else {
						final List<Trip> trips = this.townService.getTrips(this.originTown, this.destinationTown,
								FilterTrip.of(greatness, field, value));
						final StringBuffer sb = new StringBuffer();
						trips.forEach(trip -> sb.append("(").append(trip.getUnformatedPaths()).append(") "));
						this.paths = sb.toString();
					}
				}
			} catch (final ServiceException e) {
				this.takeCareException(e);
			}
		} else {
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage("Para este calculo é necessario selecionar a origem e o destino."));
		}
	}

	public String getPathCalculated() {
		String returnPath = "";
		if (CollectionUtils.isNotEmpty(this.selectedTowns) && this.selectedTowns.size() > 1) {
			try {
				final List<Path> paths = this.townService.getPath(this.selectedTowns);
				if (paths != null && !paths.isEmpty()) {
					returnPath = String.valueOf(paths.stream().mapToDouble(Path::getDistance).sum());
				} else if (this.selectedTowns.size() > 1) {
					returnPath = "NO SUCH ROUTE";
				}
			} catch (final ServiceException e) {
				this.takeCareException(e);
			}
		}
		return returnPath;
	}

	public void loadTypedGraph() {
		if (StringUtils.isNoneBlank(this.typedGraph)) {
			try {
				this.townService.saveNewGraph(this.typedGraph);
				final FacesMessage message = new FacesMessage("Grafo importado com sucesso.");
				FacesContext.getCurrentInstance().addMessage(null, message);
				this.typedGraph = null;
			} catch (final ServiceException e) {
				this.takeCareException(e);
			}
		}
	}

	public String getTypedGraph() {
		return this.typedGraph;
	}

	public void setTypedGraph(final String typedGraph) {
		this.typedGraph = typedGraph;
	}

	public Town getOriginTown() {
		return this.originTown;
	}

	public void setOriginTown(final Town originTown) {
		this.originTown = originTown;
	}

	public Town getDestinationTown() {
		return this.destinationTown;
	}

	public void setDestinationTown(final Town destinationTown) {
		this.destinationTown = destinationTown;
	}

	public String getPaths() {
		return this.paths;
	}

	public void setPaths(final String paths) {
		this.paths = paths;
	}

	public String getTripFilterField() {
		return this.tripFilterField;
	}

	public void setTripFilterField(final String tripFilterField) {
		this.tripFilterField = tripFilterField;
	}

	public String getTripFilterGreatness() {
		return this.tripFilterGreatness;
	}

	public void setTripFilterGreatness(final String tripFilterGreatness) {
		this.tripFilterGreatness = tripFilterGreatness;
	}

	public String getTripFilterValue() {
		return this.tripFilterValue;
	}

	public void setTripFilterValue(final String tripFilterValue) {
		this.tripFilterValue = tripFilterValue;
	}

	public UploadedFile getFile() {
		return this.file;
	}

	public void setFile(final UploadedFile file) {
		this.file = file;
	}

}

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui" template="/templates/default.xhtml">
  <ui:define name="content">
    <h1>Bem vindo ao portal de Consulta de Rotas de Trem!</h1>
    <p:growl id="messages" showDetail="true" />

    <p:tabView>
      <p:tab title="Carregar caminhos">
        <p:outputPanel id="uploadPanel" rendered="#{not empty request.remoteUser}">
          <h:form enctype="multipart/form-data">
            <p:outputLabel value="Selecione o arquivo:" for="graph" />
            <p:fileUpload value="#{trainRouter.file}" mode="simple" skinSimple="true" />
            <p:commandButton value="Upload" ajax="false" actionListener="#{trainRouter.upload}" />
            <br></br>
            <br></br>
            <p:outputLabel value="Ou digitando no formato correto:" for="graph" />
            <p:inputText id="graph" value="#{trainRouter.typedGraph}" />
            <p:commandButton value="Carregar" ajax="false" action="#{trainRouter.loadTypedGraph()}" />
            <br></br>
            <br></br>
          </h:form>
        </p:outputPanel>
      </p:tab>

      <p:tab title="Cálculo de distância por caminho escolhido">
        <h:form enctype="multipart/form-data">
          <p:outputLabel value="Informe as cidades que você deseja passar:" for="path" />
          <p:autoComplete id="path" multiple="true" completeMethod="#{trainRouter.selectedTown}" var="town" itemLabel="#{town.name}"
            itemValue="#{town}" forceSelection="true" converter="townConverter">
            <p:ajax event="itemSelect" listener="#{trainRouter.onSelectedTown}" update="pathCalculation" />
            <p:ajax event="itemUnselect" listener="#{trainRouter.onUnselectedTown}" update="pathCalculation" />
            <p:column>
              <h:outputText value="#{town.name}" />
            </p:column>
          </p:autoComplete>
          <br></br>
          <p:outputLabel id="pathCalculation" value="Distancia total: #{trainRouter.pathCalculated}" />
          <br></br>
          <br></br>
        </h:form>
      </p:tab>

      <p:tab title="Caminhos Possíveis">
        <h:form enctype="multipart/form-data">
          <p:outputLabel value="Informe a cidade de origem:" for="inputOrigin" />
          <p:autoComplete id="inputOrigin" value="#{trainRouter.originTown}" completeMethod="#{trainRouter.selectedTown}" var="town"
            itemLabel="#{town.name}" itemValue="#{town}" forceSelection="true" converter="townConverter">
            <p:ajax event="itemSelect" listener="#{trainRouter.onSelectedTown}" />
          </p:autoComplete>
          <br></br>
          <br></br>
          <p:outputLabel value="Informe a cidade de destino:" for="inputDestination" />
          <p:autoComplete id="inputDestination" value="#{trainRouter.destinationTown}" completeMethod="#{trainRouter.selectedTown}" var="town"
            itemLabel="#{town.name}" itemValue="#{town}" forceSelection="true" converter="townConverter">
            <p:ajax event="itemSelect" listener="#{trainRouter.onSelectedTown}" />
          </p:autoComplete>
          <br></br>
          <br></br>
          <p:accordionPanel>
            <p:ajax event="tabChange" listener="#{trainRouter.onTabChange}" />
            <p:tab id="parameterFilter" title="Filtros">
              <p:fieldset legend="Campo" style="margin-bottom:20px">
                <p:selectOneRadio id="campo" value="#{trainRouter.tripFilterField}">
                  <f:selectItem itemLabel="Paradas" itemValue="JUMPS" />
                  <f:selectItem itemLabel="Distância" itemValue="DISTANCE" />
                </p:selectOneRadio>
              </p:fieldset>
              <br></br>
              <p:fieldset legend="Grandeza" style="margin-bottom:20px">
                <p:selectOneRadio id="campoGrandeza" value="#{trainRouter.tripFilterGreatness}">
                  <f:selectItem itemLabel="Menor que" itemValue="LESS_THAN" />
                  <f:selectItem itemLabel="Exato" itemValue="EXACTLY" />
                  <f:selectItem itemLabel="No máximo" itemValue="MAXIMUM" />
                </p:selectOneRadio>
              </p:fieldset>
              <br></br>
              <p:outputLabel value="Valor para o filtro:" for="filterValue" />
              <p:inputNumber id="filterValue" value="#{trainRouter.tripFilterValue}" />
            </p:tab>
            <p:tab id="minimumPath" title="Menor Caminho">
            </p:tab>
          </p:accordionPanel>
          <br></br>
          <p:commandButton id="calculePaths" value="Calcular" action="#{trainRouter.calculePaths()}" update="outputPaths" />
          <br></br>
          <p:outputLabel id="outputPaths" value="Caminho(s): #{trainRouter.paths}" />
          <br></br>
          <br></br>
        </h:form>
      </p:tab>

    </p:tabView>

  </ui:define>
</ui:composition>

src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui" template="/templates/default.xhtml">
  <ui:define name="content">
    <h1>Bem vindo ao portal de Consulta de Rotas de Trem!</h1>


    <h:form id="login" onsubmit="document.getElementById('login').action='j_security_check';" prependId="false">
      <h:panelGrid columns="2">
        <p:outputLabel for="j_username" value="Username" />
        <p:inputText id="j_username" name="j_username" />
        <p:outputLabel for="j_password" value="Password" />
        <p:password id="j_password" name="j_password" />
        <p:commandButton id="submit" value="Login" ajax="false" />
      </h:panelGrid>
    </h:form>
  </ui:define>
</ui:composition>